"""add material test

Revision ID: 047591bbf96c
Revises: 3db54bb81cc7
Create Date: 2021-04-08 09:54:10.749114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047591bbf96c'
down_revision = '3db54bb81cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material', 'name')
    # ### end Alembic commands ###
